### ISSUE TITLE
Error: spawnSync mongoimport ENOENT

### ISSUE THREAD

**Issue by muralithiyagarajan** [bodastage/bts-ce-lite#32]
MongoDB import fails, "error","message":"Error: spawnSync mongoimport ENOENT"

**Comment by erssebaggala** [comment]
We have decided to move ahead with PostgreSQL because MongoDB will not mean most of our use cases. 

- A key requirement is we want users to generate custom reports with a familiar SQL interface. 
- Most of our queries are complex and join heavy; we were already hitting road blocks with some of the simplest queries.

We will keep a branch([install_mongodb](https://github.com/erssebaggala/bts-ce-lite/tree/install_mongodb))with the previous MongoDB code should we decide to revisit it for some specific use case.
